MapTopic:                   '/voxel_map'

TargetTopic:                '/move_base_simple/goal'

DilateRadius:               0.3

VoxelWidth:                 0.25

MapBound:                   [-50.0, 50.0, -25.0, 25.0, 0.0, 3]