MapTopic:                   '/voxel_map'

TargetTopic:                '/move_base_simple/goal'

DilateRadius:               0.1

VoxelWidth:                 0.25

MapBound:                   [-25.0, 25.0, -25.0, 25.0, 0.0, 1.5]